### ISSUE TITLE
Error when Date or DateTime field is used.

### ISSUE THREAD

**Issue by keroth-** [optimistdigital/nova-settings#13]
Hello!

Thank you for your work.

When I use a Date field or a DateTime field, an error occured: 

> Date field must cast to 'date' in Eloquent model.

Even if I use the second parameter in your addSettingsFields function.

```
\OptimistDigital\NovaSettings\NovaSettings::addSettingsFields([
    Date::make('Some date to configure', 'sample_date'),
], [
     'sample_date' => 'date',
]);
```

Same problem with DateTime field:

```
\OptimistDigital\NovaSettings\NovaSettings::addSettingsFields([
    DateTime::make('Some datetime to configure', 'sample_datetime'),
], [
     'sample_datetime' => 'datetime',
]);
```

Thank you for your help.
Regards,

Brice

**Comment by Tarpsvo** [comment]
Sorry about the delay! I fixed Date and DateTime fields and published the fix in version 2.5.0. Good luck!

**Comment by cgarofalo** [comment]
@Tarpsvo Sorry, I have upgraded to 2.5.0 and I'm still getting the error. It's a bit better than it was before, as the dates actually save to the database this time, still getting the `Date field must cast to 'date' in Eloquent model.` after save.

**Comment by Tarpsvo** [comment]
Did you add the cast to 'date'?

**Comment by cgarofalo** [comment]
@Tarpsvo Yes, it worked now. Sorry for the false alarm.

**Comment by eboye** [comment]
Hmm, I'm trying to add datetime field now and am getting the same error. Here's my setup:

NovaServiceProvider.php
```
use AppSettings;
NovaSettings::addSettingsFields( function () {
            return $this->promoPopup();
        }, [
            'promo_popup_discount_from' => 'datetime',
            'promo_popup_discount_to'   => 'datetime',
        ], 'Promo popup' );
```

AppSettings.php [Trait]
```
/**
     * @return array
     */
    static function promoPopup(): array {
        return [
            Heading::make( 'Promo popup' ),
            Boolean::make( 'Show promo popup', 'show_promo_popup' ),
            NovaDependencyContainer::make( [
                Image::make( 'Promo popup image', 'promo_popup_image' )
                     ->nullable()
                     ->help( 'Recommended image size: 780x800px it will be scalled down to 390x400px. If left empty product image will be used' ),
                Text::make( 'Promo popup title', 'promo_popup_title' )->nullable()
                    ->help( 'If left empty variation name will be used' ),
                Trix::make( 'Promo popup description', 'promo_popup_desc' )->nullable()
                    ->help( 'If left empty variation description will be used' ),
                Number::make( 'Promo popup price', 'promo_popup_price' )->min( 0 )->step( 0.01 )->nullable()
                      ->help( 'If left empty variation price will be used' ),
                Number::make( 'Promo popup discount price', 'promo_popup_discount_price' )->min( 0 )->step( 0.01 )->nullable()
                      ->help( 'If left empty variation discount price will be used' ),
                DateTime::make( 'Promo popup discount from', 'promo_popup_discount_from' )
                        ->firstDayOfWeek( 1 )->nullable(),
                DateTime::make( 'Promo popup discount to', 'promo_popup_discount_to' )
                        ->firstDayOfWeek( 1 )->nullable(),
            ] )->dependsOn( 'show_promo_popup', 1 )
        ];
    }
```

even if I remove the NovaDependencyContainer field and make it "flat" it doesn't work.

Can you help me solve this?
